Both ravel and flattern function is here to covnert  a multi-dimensional array to a single array 

Ravel function is more memory efficient than flatten() function

- because its returns flattern views of original data by avoiding creating new array in memory 

- whereas flattern function create new copy

Implementation 

In [50]:
# MULTI DIMENSION ARRAY 
import numpy as np 
x = np.arange(1 , 11 ).reshape(5,2)


In [51]:
# answers are same 
print(f" Ravel {x.ravel()} ")
print(f"np.ravel {np.ravel(x)} ")
print(f" Flatten {x.flatten() }")

 Ravel [ 1  2  3  4  5  6  7  8  9 10] 
np.ravel [ 1  2  3  4  5  6  7  8  9 10] 
 Flatten [ 1  2  3  4  5  6  7  8  9 10]


## difference 

In [52]:
y = np.ravel(x)

In [53]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
z  = x.flatten()

In [55]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
y[0] = 500 

In [60]:
x[0] # x also changes because ravel function and np.ravel both does't create a copy 

array([500,   2])

In [61]:
z[0] = 600   #but flatten generates a copy 
z[0]

600

In [59]:
x[0]

array([500,   2])