In [1]:
import numpy as np 
from matplotlib import pyplot as plt

## randint - Generates random intergers 

In [4]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

# Parameter low , high , size  , dtype 

In [10]:
np.random.randint( 2  , 5 , size = 7 )

array([3, 3, 2, 4, 3, 4, 4])

### <font color = "red " > for size to be tupple ( 2 , 5 ) say then
    - 2 is no of rows and 5 is no of columns 

In [14]:
x = np.random.randint( 2 , 5 , (2, 5 ) )
print(x) #printing the data frame itself

print() 
print(x.shape) #printing shape 

[[4 3 4 2 2]
 [3 2 2 3 2]]

(2, 5)


**If only single variable is given then**


In [15]:
np.random.randint(4)


2

**By default low will be 0 and the high will be the single parameter value**
- ## here values ranges form [0 , 4) 


In [19]:
np.random.randint(4 , size = (1 , 10 ))
#see 4 is not included 

array([[3, 0, 2, 2, 2, 2, 1, 0, 3, 0]])